(function(){
"use strict";
const A=VDMApp,root=document.getElementById("app-body"),sites=A.read("sites",{});A.frame(A.brand.name,A.brand.description);document.querySelector(".app-mark").textContent=A.brand.icon||"";
const initial={id:"t1",title:"新しいタブ",history:[],cursor:-1,sessionId:"b"+Date.now().toString(36)};
const S=A.appState({tabs:[initial],active:"t1"});let tabs=Array.isArray(S.tabs)&&S.tabs.length?S.tabs:[initial],active=S.active||tabs[0].id;
root.innerHTML='<section class="browser"><header class="browser-chrome"><div class="tab-strip"></div><div class="browser-row"><button class="icon-button" data-back aria-label="戻る">←</button><button class="icon-button" data-forward aria-label="進む">→</button><button class="icon-button" data-reload aria-label="再読み込み">↻</button><form class="browser-row" data-address-form><input class="address" name="address" aria-label="アドレス"><button class="primary">移動</button></form><button class="icon-button" data-new aria-label="新しいタブ">＋</button></div></header><div class="browser-page" data-page></div></section>';
const page=root.querySelector("[data-page]"),address=root.querySelector(".address");
function tab(){return tabs.find(x=>x.id===active)||tabs[0];}function save(){A.saveAppState({tabs,active});}
function routeParts(route){try{const u=new URL(route.includes("://")?route:"vdm://"+route);return{query:u.search.slice(1),fragment:u.hash.slice(1),host:u.host,path:u.pathname||"/",url:u};}catch(_){return{query:"",fragment:"",host:"",path:"/",url:null};}}
function worldStamp(){const s=A.state?.get?.()||{};return{worldVersion:s.worldVersion??s.world?.version??s.schemaVersion??0,pageVersion:s.pageVersion??s.world?.pageVersion??0};}
function resolve(route,meta){const safe=String(route||"vdm://home"),parts=routeParts(safe),stamp=worldStamp();if(safe==="vdm://home"||safe==="about:blank")return{url:safe,query:parts.query,fragment:parts.fragment,worldVersion:stamp.worldVersion,pageVersion:meta?.pageVersion??stamp.pageVersion,sessionId:meta?.sessionId||tab().sessionId,title:"新しいタブ",kind:"home",snapshot:null,at:Date.now()};const site=sites[parts.host],base=site?.pages?.[parts.path]||site?.pages?.["/404"];if(!site||!base)return{url:safe,query:parts.query,fragment:parts.fragment,worldVersion:stamp.worldVersion,pageVersion:stamp.pageVersion,sessionId:meta?.sessionId||tab().sessionId,title:"接続できません",kind:"error",snapshot:null,at:Date.now()};const version=(base.versions||[base]).filter(v=>!v.availableWhen||A.state.hasEvidence(v.availableWhen)).at(-1)||base;return{url:safe,query:parts.query,fragment:parts.fragment,worldVersion:stamp.worldVersion,pageVersion:version.version??meta?.pageVersion??stamp.pageVersion,sessionId:meta?.sessionId||tab().sessionId,title:version.title||site.name,kind:version.status==="deleted"||version.status===404?"deleted":"site",preset:site.preset,site:JSON.parse(JSON.stringify(site)),snapshot:JSON.parse(JSON.stringify(version)),at:Date.now()};}
function push(route,meta){const t=tab(),entry=resolve(route,meta);t.history=t.history.slice(0,t.cursor+1);t.history.push(entry);t.cursor=t.history.length-1;t.sessionId=entry.sessionId;t.title=entry.title;save();renderEntry(entry);emitRoute("push",entry);return entry;}
function replaceCurrent(route,meta){const t=tab(),entry=resolve(route,meta);if(t.cursor<0){t.history=[entry];t.cursor=0;}else t.history[t.cursor]=entry;t.sessionId=entry.sessionId;t.title=entry.title;save();renderEntry(entry);emitRoute("reload",entry);return entry;}
function current(){const t=tab();return t.history[t.cursor]||null;}function emitRoute(action,entry){A.emit("browser:route",{action,tabId:tab().id,cursor:tab().cursor,entry});}
function drawTabs(){root.querySelector(".tab-strip").innerHTML=tabs.map(t=>'<button class="tab '+(t.id===active?"active":"")+'" data-tab="'+t.id+'">'+A.esc(t.title||"新しいタブ")+'</button>').join("");root.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{active=b.dataset.tab;save();const entry=current();entry?renderEntry(entry):push("vdm://home");});}
function home(){page.innerHTML='<div class="browser-error"><h1>'+A.esc(A.brand.name)+'</h1><p>アドレスを入力するか、Searchから結果を開いてください。</p><button class="primary" data-search>Searchを開く</button></div>';page.querySelector("[data-search]").onclick=()=>A.openApp("search");}
function bindPage(){page.querySelectorAll("[data-route]").forEach(el=>el.addEventListener("click",e=>{e.preventDefault();push(el.dataset.route);}));page.querySelectorAll("form[data-route-form]").forEach(f=>f.onsubmit=e=>{e.preventDefault();const params=new URLSearchParams(new FormData(f));push(f.dataset.routeForm+(params.toString()?"?"+params:""));});window.VDMSiteInteractions?.bind(page,{navigate:route=>push(route),appState:S,save});}
function renderEntry(entry){address.value=entry.url;if(entry.kind==="home")home();else if(entry.kind==="error")page.innerHTML='<div class="browser-error"><h2>ページを表示できません</h2><p>このアドレスは端末内に保存されていません。</p><button class="ghost" data-home>ホームへ</button></div>',page.querySelector("[data-home]").onclick=()=>push("vdm://home");else if(entry.kind==="deleted")page.innerHTML='<div class="browser-error"><h2>404</h2><p>指定された記録は削除されています。</p></div>';else{const renderer=VDM_SITE_RENDERERS[entry.preset];page.innerHTML=renderer?renderer(entry.site,entry.snapshot,{route:entry.url,query:new URLSearchParams(entry.query)}):'<div class="browser-error"><h2>'+A.esc(entry.title)+'</h2></div>';VDMEvidence.observe(entry.snapshot,"open-page");bindPage();if(entry.fragment){const target=page.querySelector("#"+CSS.escape(entry.fragment));target?.scrollIntoView();}}tab().title=entry.title;drawTabs();save();}
root.querySelector("[data-address-form]").onsubmit=e=>{e.preventDefault();push(address.value);};root.querySelector("[data-back]").onclick=()=>{const t=tab();if(t.cursor>0)t.cursor-=1;const entry=current();save();if(entry){renderEntry(entry);emitRoute("back",entry);}};root.querySelector("[data-forward]").onclick=()=>{const t=tab();if(t.cursor+1<t.history.length)t.cursor+=1;const entry=current();save();if(entry){renderEntry(entry);emitRoute("forward",entry);}};root.querySelector("[data-reload]").onclick=()=>{const entry=current();replaceCurrent(entry?.url||"vdm://home",{sessionId:tab().sessionId});};root.querySelector("[data-new]").onclick=()=>{const id="t"+Date.now().toString(36);tabs.push({id,title:"新しいタブ",history:[],cursor:-1,sessionId:"b"+Date.now().toString(36)});active=id;save();push("vdm://home");};
window.addEventListener("message",e=>{if(e.data?.type==="VDM_ROUTE")push(e.data.route,e.data);});window.addEventListener("vdm-open-payload",e=>e.detail?.route&&push(e.detail.route,e.detail));
drawTabs();current()?renderEntry(current()):push("vdm://home");
})();

