(function(){
document.head.insertAdjacentHTML("beforeend",'<style>@media(max-width:720px){.files-layout{grid-template-columns:1fr;grid-template-rows:auto minmax(0,1fr)}.tree{display:flex!important;gap:4px;overflow:auto;padding:7px;border-right:0;border-bottom:1px solid var(--line)}.tree h3{display:none}.tree .nav-button{width:auto;white-space:nowrap}}</style>');
"use strict";const A=VDMApp,D=A.read("files",{}),root=document.getElementById("app-body");A.frame(A.brand.name,A.brand.description);document.querySelector(".app-mark").textContent=A.brand.icon||"";
const S=A.appState({folder:"root",active:null,query:"",recent:[],trash:[],trashMeta:{},deleted:[],mobile:"list"});function save(){A.saveAppState(S);}const source=()=> (D.items||[]).filter(x=>!S.deleted.includes(x.id));
function items(){let list=source();if(S.folder==="trash")list=list.filter(x=>S.trash.includes(x.id));else if(S.folder==="recent")list=list.filter(x=>S.recent.includes(x.id)&&!S.trash.includes(x.id));else list=list.filter(x=>!S.trash.includes(x.id)&&(x.folder||"root")===S.folder);return list.filter(x=>!S.query||VDMText.includesAll([x.name,x.type,x.tags].join(" "),S.query));}
function preview(x){if(!x)return'<div class="empty">ファイルを選択してください</div>';let p="";if(x.type==="image")p='<img class="post-media" src="'+A.esc(x.src)+'" alt="'+A.esc(x.alt||"")+'">';else if(x.type==="audio")p='<button class="primary" data-open-media>音声を開く</button>';else p='<div class="file-preview">'+A.esc(x.text||x.transcript||x.pdfText||"プレビューはありません")+'</div>';const inTrash=S.trash.includes(x.id);return'<button class="ghost mobile-only" data-mobile-back>← 一覧</button><h2>'+A.esc(x.name)+'</h2>'+p+'<dl><dt>種類</dt><dd>'+A.esc(x.type||"file")+'</dd><dt>更新日</dt><dd>'+A.esc(x.modified||"不明")+'</dd><dt>サイズ</dt><dd>'+A.esc(x.size||"不明")+'</dd></dl><div class="toolbar"><button class="ghost" data-download>ダウンロード</button>'+(inTrash?'<button class="primary" data-restore>元のフォルダーへ復元</button><button class="ghost danger" data-delete-forever>完全に削除</button>':'<button class="ghost" data-trash>ごみ箱へ</button>')+'</div>';}
function render(){const x=source().find(i=>i.id===S.active);root.innerHTML='<section class="files-layout"><nav class="tree"><h3>フォルダー</h3><button class="nav-button" data-folder="root">ホーム</button>'+(D.folders||[]).map(f=>'<button class="nav-button" data-folder="'+f.id+'">'+A.esc(f.name)+'</button>').join("")+'<button class="nav-button" data-folder="recent">最近使った項目</button><button class="nav-button" data-folder="trash">ごみ箱</button></nav><main class="file-table '+(S.mobile==="list"?"mobile-active":"")+'"><div class="breadcrumb"><span>'+A.esc(S.folder)+'</span><input class="field" data-search value="'+A.esc(S.query)+'" placeholder="現在のフォルダーを検索"></div>'+items().map(i=>'<button class="file-row" data-file="'+i.id+'"><strong>'+A.esc(i.name)+'</strong><span>'+A.esc(i.type||"file")+'</span><small>'+A.esc(i.modified||"")+'</small></button>').join("")+(items().length?"":'<div class="empty">このフォルダーは空です</div>')+'</main><aside class="detail-pane '+(S.mobile==="detail"?"mobile-active":"")+'">'+preview(x)+'</aside></section>';bind(x);}
function moveToTrash(x){if(!S.trash.includes(x.id))S.trash.push(x.id);S.trashMeta[x.id]={folder:x.folder||"root",trashedAt:new Date().toISOString()};S.active=null;S.mobile="list";save();render();}
function restore(x){S.trash=S.trash.filter(id=>id!==x.id);delete S.trashMeta[x.id];S.folder=x.folder||"root";S.active=x.id;save();render();}
function confirmDelete(x){const dialog=document.createElement("dialog");dialog.innerHTML='<form method="dialog" class="dialog-card"><h2>完全に削除しますか</h2><p>'+A.esc(x.name)+' は復元できなくなります。</p><button class="ghost" value="cancel">キャンセル</button><button type="button" class="primary" data-hold-delete>長押しして完全削除</button><p data-hold-status>1.2秒長押ししてください</p></form>';root.appendChild(dialog);dialog.showModal();let hold;const button=dialog.querySelector("[data-hold-delete]"),cancel=()=>clearTimeout(hold);button.onpointerdown=()=>{dialog.querySelector("[data-hold-status]").textContent="そのまま押し続けてください…";hold=setTimeout(()=>{S.deleted.push(x.id);S.trash=S.trash.filter(id=>id!==x.id);S.recent=S.recent.filter(id=>id!==x.id);delete S.trashMeta[x.id];S.active=null;save();dialog.close();render();},1200);};button.onpointerup=button.onpointerleave=cancel;dialog.addEventListener("close",()=>dialog.remove());}
function bind(x){root.querySelectorAll("[data-folder]").forEach(b=>b.onclick=()=>{S.folder=b.dataset.folder;S.active=null;S.query="";S.mobile="list";save();render();});root.querySelector("[data-search]")?.addEventListener("input",e=>{S.query=e.target.value;save();render();});root.querySelectorAll("[data-file]").forEach(b=>b.onclick=()=>{S.active=b.dataset.file;S.mobile="detail";if(!S.recent.includes(S.active)&&S.folder!=="trash")S.recent.unshift(S.active);save();render();VDMEvidence.observe(source().find(i=>i.id===S.active),"open-file");});root.querySelector("[data-mobile-back]")?.addEventListener("click",()=>{S.mobile="list";save();render();});root.querySelector("[data-open-media]")?.addEventListener("click",()=>VDMMedia.open(x));root.querySelector("[data-trash]")?.addEventListener("click",()=>moveToTrash(x));root.querySelector("[data-restore]")?.addEventListener("click",()=>restore(x));root.querySelector("[data-delete-forever]")?.addEventListener("click",()=>confirmDelete(x));root.querySelector("[data-download]")?.addEventListener("click",()=>{if(!x.src)return;const a=document.createElement("a");a.href=localMediaUrl(x.src);a.download=x.name;a.click();VDMEvidence.observe(x,"download");});}render();
})();
