(function(){
"use strict";
const A=window.VDMApp,D=A.read("search",{}),T=window.VDMText,root=document.getElementById("app-body");
A.frame(A.brand.name,A.brand.description);document.querySelector(".app-mark").textContent=A.brand.icon||"";
const local=A.appState({view:"home",query:"",kind:"all",history:[],sessions:[],sessionId:null,sequence:0});
const available=(item)=>!item.availableWhen||item.availableWhen.every((id)=>A.state&&A.state.hasEvidence&&A.state.hasEvidence(id));
const versions=(item)=>{const list=item.versions||[item];return list.filter(available).at(-1)||item;};
const matches=(item,q)=>T.includesAll([item.title,item.snippet,item.path,item.keywords,item.intents].flat().join(" "),q);
function suggestions(q){const known=[...(D.vocabulary||[]),...(D.discoveredTerms||[])],direct=known.filter(x=>T.includesAll(x,q)||T.includesAll(q,x)).slice(0,6),typo=window.VDMContentEngine.suggest(q,known);return[...new Set([...direct,...(typo?[typo]:[])])].slice(0,6);}
function persist(patch){Object.assign(local,patch);A.saveAppState(local);}
function shell(inner){root.innerHTML='<section class="search-shell">'+inner+'</section>';}
function search(q,kind,reason){q=String(q||"").trim();if(!q){renderHome();return;}kind=kind||local.kind||"all";const all=(D.records||[]).filter(available).map(versions),results=all.filter(x=>(kind==="all"||x.kind===kind)&&matches(x,q)),suggestion=window.VDMContentEngine.suggest(q,[...(D.vocabulary||[]),...(D.discoveredTerms||[])]),state=A.state?.get?.()||{};local.sequence=(Number(local.sequence)||0)+1;const session={id:"s"+Date.now().toString(36)+"-"+local.sequence.toString(36),query:q,kind,at:Date.now(),reason:reason||"search",resultIds:results.map(x=>x.id),snapshot:JSON.parse(JSON.stringify(results)),worldVersion:state.worldVersion??state.world?.version??state.schemaVersion??0,pageVersion:state.pageVersion??state.world?.pageVersion??0,suggestion};local.sessions=[session,...local.sessions].slice(0,20);const retained=new Set(local.sessions.map(x=>x.id));local.history=[{sessionId:session.id,query:q,kind,at:session.at,worldVersion:session.worldVersion,pageVersion:session.pageVersion},...local.history].filter((h,i,list)=>retained.has(h.sessionId)&&list.findIndex(x=>x.sessionId===h.sessionId)===i).slice(0,20);persist({view:"results",query:q,kind,sessionId:session.id});renderResults(results,suggestion,session);return session;}
function restoreSession(id){const session=local.sessions.find(x=>x.id===id);if(!session){renderView("history");return;}persist({view:"results",query:session.query,kind:session.kind,sessionId:session.id});renderResults(session.snapshot||[],session.suggestion||"",session);}
function searchBox(value){return '<form class="search-box" data-search-form><span aria-hidden="true">⌕</span><input name="q" value="'+A.esc(value||"")+'" autocomplete="off" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-label="検索"><button class="primary">検索</button><div class="suggestions" role="listbox" hidden></div></form>';}
function bindSearch(){const form=root.querySelector("[data-search-form]"),input=form.querySelector("input"),box=form.querySelector(".suggestions");form.addEventListener("submit",e=>{e.preventDefault();search(input.value,local.kind,"search");});input.addEventListener("input",()=>{const items=suggestions(input.value);box.innerHTML=items.map(x=>'<button type="button" role="option">'+A.esc(x)+'</button>').join("");box.hidden=!items.length;input.setAttribute("aria-expanded",String(items.length>0));box.querySelectorAll("button").forEach(b=>b.onclick=()=>{input.value=b.textContent;search(input.value,local.kind,"suggestion");});});input.addEventListener("keydown",e=>{const opts=[...box.querySelectorAll("button")];let i=opts.indexOf(document.activeElement);if(e.key==="ArrowDown"&&opts.length){e.preventDefault();opts[Math.min(i+1,opts.length-1)].focus();}});}
function renderHome(){persist({view:"home",sessionId:null});shell('<div class="search-home"><div class="brand-word">'+A.esc(A.brand.name)+'</div>'+searchBox("")+'<div class="toolbar"><button class="ghost" data-view="history">履歴</button><button class="ghost" data-view="about">この検索について</button></div></div>');bindSearch();root.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>renderView(b.dataset.view));}
function renderResults(results,suggestion,session){const tabs=["all","images","news"].map(k=>'<button class="ghost" data-kind="'+k+'" aria-selected="'+(local.kind===k)+'">'+({all:"すべて",images:"画像",news:"ニュース"}[k])+'</button>').join("");const rows=results.map(r=>'<article class="result '+(r.status==="deleted"?"deleted":"")+'"><div class="result-path">'+A.esc(r.path||r.url||"local")+'</div><h3><button class="nav-button" data-result="'+A.esc(r.id)+'">'+A.esc(r.title)+'</button></h3><p>'+A.esc(r.snippet||"")+'</p></article>').join("")||'<div class="empty"><div><h2>一致する結果はありません</h2><p>語句を変えるか、履歴を確認してください。</p></div></div>';const did=suggestion?'<p>もしかして: <button class="nav-button" data-suggest>'+A.esc(suggestion)+'</button></p>':"";shell('<div class="content"><div class="toolbar"><button class="icon-button" data-home aria-label="ホーム">⌂</button>'+searchBox(local.query)+'</div><div class="kind-tabs">'+tabs+'</div>'+did+'<div class="results-layout"><main><p class="muted">'+results.length+' 件・セッション '+A.esc(session.id)+'</p>'+rows+'</main><aside class="knowledge card"><h3>検索セッション</h3><p>'+A.esc(local.query)+'</p><button class="ghost" data-view="history">履歴を見る</button></aside></div></div>');bindSearch();root.querySelector("[data-home]").onclick=renderHome;root.querySelectorAll("[data-kind]").forEach(b=>b.onclick=()=>{local.kind=b.dataset.kind;search(local.query,local.kind,"kind");});root.querySelector("[data-suggest]")?.addEventListener("click",()=>search(suggestion,local.kind,"suggestion"));root.querySelector("[data-view]")?.addEventListener("click",()=>renderView("history"));root.querySelectorAll("[data-result]").forEach(b=>b.onclick=()=>openResult(results.find(x=>x.id===b.dataset.result),session));}
function openResult(item,session){if(!item)return;if(item.status==="deleted"||item.status==="404"){shell('<div class="browser-error"><h2>ページを表示できません</h2><p>索引には痕跡が残っていますが、本文は利用できません。</p><button class="primary" data-back>検索へ戻る</button></div>');root.querySelector("[data-back]").onclick=()=>restoreSession(session.id);return;}window.VDMEvidence.observe(item,"open-result");if(item.route){A.openApp("browser",{route:item.route,source:"search",sessionId:local.sessionId});}else if(item.media){window.VDMMedia.open(item.media);}else{shell('<div class="content"><button class="ghost" data-back>← 結果へ</button><article class="card knowledge"><h1>'+A.esc(item.title)+'</h1><p>'+A.esc(item.body||item.snippet||"")+'</p></article></div>');root.querySelector("[data-back]").onclick=()=>restoreSession(session.id);}}
function renderView(view){persist({view});if(view==="about"){shell('<div class="content"><button class="ghost" data-home>←</button><article class="card knowledge"><h1>この検索について</h1><p>'+A.esc(D.about||"ローカル索引です。")+'</p><h2>検索オプション</h2><p>NFKC正規化、空白・記号・ハイフン差、語順差を吸収します。</p></article></div>');root.querySelector("[data-home]").onclick=renderHome;return;}const rows=local.history.map(h=>'<div class="list-item history-row"><button class="nav-button" data-session="'+A.esc(h.sessionId)+'">'+A.esc(h.query)+'</button><small>'+new Date(h.at).toLocaleString("ja-JP")+' · '+A.esc(h.sessionId)+'</small></div>').join("")||'<div class="empty">検索履歴はありません</div>';shell('<div class="content"><button class="ghost" data-home>← ホーム</button><h1>検索履歴</h1><div class="list">'+rows+'</div></div>');root.querySelector("[data-home]").onclick=renderHome;root.querySelectorAll("[data-session]").forEach(b=>b.onclick=()=>restoreSession(b.dataset.session));}
if(local.view==="results"&&local.query)search(local.query,local.kind,"reload");else if(local.view==="history"||local.view==="about")renderView(local.view);else renderHome();
})();



