(function(){
"use strict";
const A=VDMApp,D=A.read("mail",{}),root=document.getElementById("app-body"),ATT=VDMLocalAttachment;A.frame(A.brand.name,A.brand.description);document.querySelector(".app-mark").textContent=A.brand.icon||"";
const S=A.appState({folder:"inbox",active:null,read:[],starred:[],archived:[],trashed:[],drafts:[],sent:[],mobile:"list",composeAttachments:[]});function save(){A.saveAppState(S);}const all=()=>[...(S.sent||[]),...(S.drafts||[]),...(D.messages||[])];
function inFolder(m){if(S.folder==="trash")return S.trashed.includes(m.id);if(S.folder==="archive")return S.archived.includes(m.id)&&!S.trashed.includes(m.id);if(S.folder==="starred")return S.starred.includes(m.id)&&!S.trashed.includes(m.id);if(S.folder==="sent")return m.folder==="sent"&&!S.trashed.includes(m.id);if(S.folder==="drafts")return m.folder==="drafts"&&!S.trashed.includes(m.id);return(m.folder||"inbox")==="inbox"&&!S.archived.includes(m.id)&&!S.trashed.includes(m.id);}
function folders(){return'<nav class="mail-folders"><button class="primary" data-compose>新規作成</button>'+["inbox","starred","sent","drafts","archive","trash"].map(f=>'<button class="nav-button" data-folder="'+f+'" aria-current="'+(S.folder===f?"page":"false")+'">'+({inbox:"受信トレイ",starred:"スター",sent:"送信済み",drafts:"下書き",archive:"アーカイブ",trash:"ごみ箱"}[f])+'</button>').join("")+'</nav>';}
function list(){const rows=all().filter(inFolder);return'<section class="mail-list '+(S.mobile==="list"?"mobile-active":"")+'"><div class="toolbar"><input class="field" data-search placeholder="メールを検索"></div>'+rows.map(m=>'<button class="mail-row '+(!S.read.includes(m.id)?"unread":"")+'" data-mail="'+m.id+'"><span><strong>'+A.esc(m.from?.name||m.from||m.to||"下書き")+'</strong><br>'+A.esc(m.subject||"(件名なし)")+'<small>'+A.esc(m.preview||String(m.body||"").slice(0,60))+'</small></span><span>'+(S.starred.includes(m.id)?"★":"☆")+'<br><small>'+A.esc(m.date||"")+'</small></span></button>').join("")+'</section>';}
function attachments(m){return(m.attachments||[]).map((x,i)=>'<button class="attachment" data-attachment="'+i+'">'+A.esc(x.name||x.label||"添付ファイル")+' <small>'+A.esc(x.size?Math.ceil(x.size/1024)+"KiB":"")+'</small></button>').join("");}
function body(m){if(!m)return'<article class="mail-body mobile-active"><div class="empty">メールを選択してください</div></article>';return'<article class="mail-body '+(S.mobile==="body"?"mobile-active":"")+'"><button class="ghost mobile-only" data-mobile-back>← 一覧</button><div class="mail-actions"><button class="ghost" data-action="star">'+(S.starred.includes(m.id)?"★":"☆")+'</button><button class="ghost" data-action="unread">未読に戻す</button><button class="ghost" data-action="archive">アーカイブ</button><button class="ghost" data-action="trash">'+(S.trashed.includes(m.id)?"復元":"削除")+'</button><button class="ghost" data-action="reply">返信</button><button class="ghost" data-action="replyall">全員に返信</button><button class="ghost" data-action="forward">転送</button></div><header class="mail-header"><h1>'+A.esc(m.subject||"(件名なし)")+'</h1><p><strong>差出人:</strong> '+A.esc(m.from?.address||m.from||"")+'<br><strong>宛先:</strong> '+A.esc(Array.isArray(m.to)?m.to.join(", "):m.to||"")+'<br><strong>日時:</strong> '+A.esc(m.date||"")+'</p></header><div class="mail-content">'+String(m.html||A.esc(m.body||"")).replace(/\n/g,"<br>")+'</div><div class="toolbar">'+attachments(m)+'</div>'+(m.quoted?'<blockquote class="quoted">'+A.esc(m.quoted)+'</blockquote>':"")+'</article>';}
function pending(){return S.composeAttachments.length?'<div class="attachment-preview">'+S.composeAttachments.map(x=>'<span class="attachment">'+A.esc(x.name)+' <small>'+Math.ceil(x.size/1024)+'KiB</small><button type="button" data-remove-attachment="'+x.id+'">×</button></span>').join("")+'<small>端末内保存・1件512KiB／合計2MiBまで</small></div>':"";}
function composer(base){base=base||{};return'<article class="mail-body mobile-active"><button class="ghost mobile-only" data-mobile-back>←</button><form class="compose-sheet" data-send><label>宛先<input class="field" name="to" value="'+A.esc(base.to||"")+'"></label><details><summary>CC / BCC</summary><label>CC<input class="field" name="cc" value="'+A.esc(base.cc||"")+'"></label><label>BCC<input class="field" name="bcc" value="'+A.esc(base.bcc||"")+'"></label></details><label>件名<input class="field" name="subject" value="'+A.esc(base.subject||"")+'"></label><textarea class="field" name="body" rows="12">'+A.esc(base.body||"")+'</textarea>'+pending()+'<div class="toolbar"><button type="button" class="ghost" data-add-attachment>添付を追加</button><input type="file" data-file-input accept="image/*,audio/*,.txt,.md,.csv,.json,.pdf" hidden><button class="primary">送信</button><button type="button" class="ghost" data-save-draft>下書き保存</button></div><p class="muted" data-attachment-status role="status"></p></form></article>';}
function render(compose){const m=all().find(x=>x.id===S.active);root.innerHTML='<section class="mail-layout">'+folders()+list()+(compose?composer(compose):body(m))+'</section>';bind(compose);}
function composeFor(kind,m){const from=m?.from?.address||m?.from||"";S.composeAttachments=kind==="forward"?JSON.parse(JSON.stringify(m.attachments||[])):[];if(kind==="forward")return{subject:"Fwd: "+(m.subject||""),body:"\n\n---------- 転送メール ----------\n"+(m.body||"")};return{to:from,cc:kind==="replyall"?(m.cc||[]).join(", "):"",subject:"Re: "+(m.subject||""),body:"\n\n"+(m.body||"").split("\n").map(x=>"> "+x).join("\n")};}
async function chooseAttachment(input){const status=root.querySelector("[data-attachment-status]");try{S.composeAttachments.push(await ATT.fromFile(input.files?.[0],S.composeAttachments));save();render(currentCompose());}catch(error){status.textContent=error.message;input.value="";}}
let composeCache=null;function currentCompose(){if(!composeCache)return{};const form=root.querySelector("[data-send]");if(!form)return composeCache;const fd=new FormData(form);composeCache={to:fd.get("to"),cc:fd.get("cc"),bcc:fd.get("bcc"),subject:fd.get("subject"),body:fd.get("body")};return composeCache;}
function bind(compose){composeCache=compose||null;root.querySelectorAll("[data-folder]").forEach(b=>b.onclick=()=>{S.folder=b.dataset.folder;S.active=null;S.mobile="list";save();render();});root.querySelectorAll("[data-mail]").forEach(b=>b.onclick=()=>{S.active=b.dataset.mail;if(!S.read.includes(S.active))S.read.push(S.active);S.mobile="body";save();render();VDMEvidence.observe(all().find(x=>x.id===S.active),"open-mail");});root.querySelector("[data-search]")?.addEventListener("input",e=>root.querySelectorAll("[data-mail]").forEach(b=>b.hidden=!VDMText.includesAll(b.textContent,e.target.value)));root.querySelector("[data-compose]")?.addEventListener("click",()=>{S.composeAttachments=[];render({});});root.querySelector("[data-mobile-back]")?.addEventListener("click",()=>{S.mobile="list";save();render();});const m=all().find(x=>x.id===S.active);root.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==="star"){const i=S.starred.indexOf(m.id);i<0?S.starred.push(m.id):S.starred.splice(i,1);}else if(a==="unread"){S.read=S.read.filter(id=>id!==m.id);S.mobile="list";}else if(a==="archive"){if(!S.archived.includes(m.id))S.archived.push(m.id);S.mobile="list";}else if(a==="trash"){const i=S.trashed.indexOf(m.id);i<0?S.trashed.push(m.id):S.trashed.splice(i,1);S.mobile="list";}else return render(composeFor(a,m));save();render();});root.querySelectorAll("[data-attachment]").forEach(b=>b.onclick=()=>{const x=m.attachments[+b.dataset.attachment];ATT.open(x);VDMEvidence.observe(Object.assign({},m,{evidenceId:x.evidenceId,evidenceOn:x.evidenceOn}),"open-attachment");});const form=root.querySelector("[data-send]");if(form){root.querySelector("[data-add-attachment]").onclick=()=>root.querySelector("[data-file-input]").click();root.querySelector("[data-file-input]").onchange=e=>chooseAttachment(e.target);root.querySelectorAll("[data-remove-attachment]").forEach(b=>b.onclick=()=>{const draft=currentCompose();S.composeAttachments=S.composeAttachments.filter(x=>x.id!==b.dataset.removeAttachment);save();render(draft);});const collect=()=>{const fd=new FormData(form);return{id:"local-mail-"+Date.now(),folder:"sent",to:fd.get("to"),cc:fd.get("cc"),bcc:fd.get("bcc"),subject:fd.get("subject"),body:fd.get("body"),date:new Date().toLocaleString("ja-JP"),attachments:JSON.parse(JSON.stringify(S.composeAttachments))};};form.onsubmit=e=>{e.preventDefault();S.sent.unshift(collect());S.composeAttachments=[];S.folder="sent";S.mobile="list";save();render();};root.querySelector("[data-save-draft]").onclick=()=>{const d=collect();d.folder="drafts";S.drafts.unshift(d);S.composeAttachments=[];S.folder="drafts";S.mobile="list";save();render();};}}
render();
})();

